# Generated by Django 5.2.7 on 2025-11-02 17:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form_definitions', to='tramites.tramite')),
            ],
            options={
                'verbose_name': 'Definicion de formulario',
                'verbose_name_plural': 'Definiciones de formulario',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FormVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('changelog', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='formularios.formdefinition')),
            ],
            options={
                'verbose_name': 'Version de formulario',
                'verbose_name_plural': 'Versiones de formulario',
                'ordering': ('form', '-version'),
                'unique_together': {('form', 'version')},
            },
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='active_version',
            field=models.ForeignKey(blank=True, help_text='Version marcada como activa para uso por defecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_definitions', to='formularios.formversion'),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Identificador estandar sin espacios', max_length=100)),
                ('label', models.CharField(max_length=160)),
                ('type', models.CharField(choices=[('text', 'Texto'), ('textarea', 'Texto multilinea'), ('number', 'Numero'), ('date', 'Fecha'), ('email', 'Email'), ('phone', 'Telefono'), ('select', 'Seleccion'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('file', 'Archivo')], max_length=20)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('validations', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=list)),
                ('form_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='formularios.formversion')),
            ],
            options={
                'verbose_name': 'Campo de formulario',
                'verbose_name_plural': 'Campos de formulario',
                'ordering': ('form_version', 'order', 'id'),
                'unique_together': {('form_version', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='formdefinition',
            unique_together={('name', 'tramite')},
        ),
    ]
