# Generated by Django 5.2.7 on 2025-11-02 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TramiteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de trámite',
                'verbose_name_plural': 'Tipos de trámite',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.ForeignKey(help_text='Tipo de trámite al que pertenece', on_delete=django.db.models.deletion.PROTECT, related_name='tramites', to='tramites.tramitetype')),
            ],
            options={
                'verbose_name': 'Trámite',
                'verbose_name_plural': 'Trámites',
                'ordering': ('title',),
                'indexes': [models.Index(fields=['slug'], name='tramites_tr_slug_780560_idx'), models.Index(fields=['is_active'], name='tramites_tr_is_acti_0359df_idx')],
            },
        ),
    ]
