# Generated by Django 5.0 on 2025-10-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tramite',
            name='tipo',
            field=models.CharField(choices=[('catalogo', 'Catálogo'), ('formulario', 'Formulario')], default='catalogo', max_length=20),
        ),
    ]
